# ==============================================================================
# Pull request clone ===========================================================
# ==============================================================================
# Use plugin to checkout pull requests for caching issue:
# https://github.com/drone/drone/issues/2390
# ==============================================================================
clone:
  git:
    image: plugins/git:next
    when:
      event: [ push, tag ]

services:
  docker:
    image: docker:18-dind
    privileged: true

pipeline:

  # Test image build.
  build:
    image: docker:18-dind
    environment:
      - DOCKER_HOST=tcp://docker:2375
    commands:
      - sleep 10
      - docker ps
      - docker build -t openeuropa/triple-store-dev .

  # Deploy image.
  publish-docker-image:
    image: plugins/docker
    repo: openeuropa/triple-store-dev
    dockerfile: Dockerfile
    secrets: [ docker_username, docker_password ]
    when:
      event: [ push ]
      branch: master

  publish-docker-image-tag:
    image: plugins/docker
    repo: openeuropa/triple-store-dev
    dockerfile: Dockerfile
    tags:
      - ${DRONE_TAG}
    secrets: [ docker_username, docker_password ]
    when:
      event: [ tag ]
      branch: master
