pipeline:
  publish-docker-image:
    group: docker-image
    image: plugins/docker
    repo: openeuropa/triple-store
    dockerfile: Dockerfile
    secrets: [ docker_username, docker_password ]
    when:
      event: push
